### ISSUE TITLE
Missing parentheses in call to 'print'

### ISSUE THREAD

**Issue by hemebond** [saurabh-hirani/icinga2_api#2]
Version 0.0.6, installed via PIP.

```  File "/lib/python3.5/site-packages/icinga2_api/api.py", line 82
    print 'url: %s' % url
                  ^
SyntaxError: Missing parentheses in call to 'print'```

**Comment by saurabh-hirani** [comment]
Sorry for the late reply. I haven't been playing with icinga2 for over an year now. I am not using python3 for this API. So my print calls are statements and not functions. None of the print calls are using parenthesis in this repo.

**Comment by hemebond** [comment]
My bad. For some reason I thought the API was designed to work with Python 3 as well. Closing.
